### ISSUE TITLE
lifespan of maps

### ISSUE THREAD

**Issue by iomn** [aktionskarten/backend#11]
Maps should have a fixed lifespan after the event took place. For instance like 30 days or maybe even configurable like in etherpad (1d, 60d or 1y).  If this lifespan is expired the map should be deleted automatically.

**Comment by kohllisti** [comment]
maps now have a lifespan of 30 days.

**Comment by waschbeer** [comment]
So, apparently, maps older than 30 days are now filtered out when viewing available maps, however not yet deleted from the db.
Use following in `app/cli/__init__.py` to delete old maps from DB:
```
 from app.models import Map, db

(db.session.query(Map).filter_by(outdated=True).all()
```

**Comment by iomn** [comment]
Achieved through adding a cronjob for `flask remove-outdated-maps`
