### ISSUE TITLE
render polygons

### ISSUE THREAD

**Issue by kohllisti** [aktionskarten/backend#5]
Currently polygones are not rendered in the preview.

**Comment by waschbeer** [comment]
works for me^^ :cookie:

**Comment by iomn** [comment]
see https://github.com/aktionskarten/aktionskarten.js/issues/13

**Comment by iomn** [comment]
Styles should contain default values for color and so on

**Comment by kohllisti** [comment]
@iomn I assume this is no issue anymore right?

**Comment by iomn** [comment]
Yeah, has been fixed some time ago.
